//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret.ENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public string Yetki { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    }
}
