//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret.ENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int SepetID { get; set; }
        public string KullaniciAd { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> Tutar { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
