//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret.ENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> AltKategoriID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
    
        public virtual AltKategori AltKategori { get; set; }
    }
}
